Repository mash-up-kr/Dorabangs_iOS, pull requests merged in 2024-07, with the labels that each got.

#28 🎨 디자인시스템 폴더 바텀 시트 구현
  Projects/Core/Models/dummy.swift
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_select.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_select.imageset/ic_select.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_select.imageset/ic_select@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_select.imageset/ic_select@3x.png
  Projects/DesignSystem/DesignSystemKit/Sources/ActionSheet/LKActionSheet.swift
  Projects/DesignSystem/DesignSystemKit/Sources/FolderBottomSheet/FolderBottomSheet.swift
  Projects/DesignSystem/DesignSystemKit/Sources/FolderBottomSheet/FolderList.swift
  Projects/DesignSystem/DesignSystemKit/Sources/FolderBottomSheet/FolderView.swift
  Projects/DesignSystem/DesignSystemKit/Sources/FolderBottomSheet/NewFolderView.swift
  Projects/DesignSystem/DesignSystemKit/Sources/ViewModifiers/BottomSheet.swift
  Projects/DesignSystem/DesignSystemUI/Sources/Component/FolderBottomSheetPreview.swift
  Projects/DesignSystem/DesignSystemUI/Sources/ContentView.swift
Labels: FEATURE

#38 ShareExtension 타겟 추가 및 ShareViewController 구현
  Projects/App/InfoPlists/Info.plist
  Projects/App/InfoPlists/ShareExtension-Info.plist
  Projects/App/Project.swift
  Projects/App/ShareExtension/ShareViewController.swift
  Projects/App/Sources/DorabangsApp.swift
  Projects/ConfigurationFiles/debug-ShareExtension.xcconfig
  Projects/ConfigurationFiles/debug.xcconfig
  Projects/ConfigurationFiles/release-ShareExtension.xcconfig
  Projects/ConfigurationFiles/shared-ShareExtension.xcconfig
  Projects/Features/Coordinator/AppCoordinator/AppCoordinator.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinator.swift
  Projects/Features/Coordinator/TabCoordinator/TabCoordinator.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE, ⭐️⭐️ㅤ

#40 Regular FontWeight 적용 안 되는 문제 수정
  Projects/DesignSystem/DesignSystemKit/Sources/ViewModifiers/Font.swift
Labels: DESIGN, ⭐️⭐️ㅤ

#42 새 폴더 추가 화면 구현
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Coordinator/SaveURLCoordinator/SaveURLCoordinator.swift
  Projects/Features/Coordinator/SaveURLCoordinator/SaveURLCoordinatorView.swift
  Projects/Features/Scene/CreateNewFolderScene/CreateNewFolder.swift
  Projects/Features/Scene/CreateNewFolderScene/CreateNewFolderView.swift
  Projects/Features/Scene/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE, ⭐️⭐️ㅤ

#45 폴더 선택 화면 구현
  Projects/Core/Models/URLMetadata.swift
  Projects/Core/Models/dummy.swift
  Projects/Core/Project.swift
  Projects/Core/Services/URLMetadataClient.swift
  Projects/Core/Services/URLValidatorClient.swift
  Projects/Core/Services/dummy.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Coordinator/SaveURLCoordinator/SaveURLCoordinator.swift
  Projects/Features/Coordinator/SaveURLCoordinator/SaveURLCoordinatorView.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/SaveURLScene/SaveURL.swift
  Projects/Features/Scene/SelectFolderScene/SelectFolder.swift
  Projects/Features/Scene/SelectFolderScene/SelectFolderView.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE, ⭐️⭐️ㅤ

#49 내비게이션 버그 수정
  Projects/App/Sources/Extensions/UINavigationController+NavigationBar.swift
  Projects/DesignSystem/DesignSystemKit/Sources/FolderBottomSheet/FolderBottomSheet.swift
  Projects/DesignSystem/DesignSystemKit/Sources/FolderBottomSheet/FolderList.swift
  Projects/DesignSystem/DesignSystemKit/Sources/FolderBottomSheet/FolderView.swift
  Projects/DesignSystem/DesignSystemKit/Sources/FolderBottomSheet/NewFolderView.swift
  Projects/DesignSystem/DesignSystemKit/Sources/TabBar/LKTabBar.swift
  Projects/DesignSystem/DesignSystemKit/Sources/TopScrollBar/LKTopScrollBar.swift
  Projects/DesignSystem/DesignSystemKit/Sources/TopScrollBar/LKTopTabView.swift
  Projects/DesignSystem/DesignSystemKit/Sources/ViewModifiers/BottomSheet.swift
  Projects/DesignSystem/DesignSystemUI/Sources/Common/AddTextOptionView.swift
  Projects/DesignSystem/DesignSystemUI/Sources/Component/FolderBottomSheetPreview.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorView.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinator.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinatorView.swift
  Projects/Features/Coordinator/SaveURLCoordinator/SaveURLCoordinatorView.swift
  Projects/Features/Coordinator/StorageBoxCoordinator/StorageBoxCoordinatorView.swift
  Projects/Features/Coordinator/TabCoordinator/TabCoordinatorView.swift
  Projects/Features/Scene/CreateNewFolderScene/CreateNewFolderView.swift
  Projects/Features/Scene/HomeScene/HomeView.swift
  Projects/Features/Scene/SaveURLScene/SaveURLView.swift
  Projects/Features/Scene/StorageBoxScene/StorageBoxView.swift
Labels: BUG, ⭐️⭐️ㅤ

#51 링크 저장 기능 구현
  .swiftformat
  Projects/App/ShareExtension/ShareViewController.swift
  Projects/App/Sources/DorabangsApp.swift
  Projects/Core/Models/SharedClipboardToast.swift
  Projects/DesignSystem/DesignSystemKit/Sources/ViewModifiers/ClipboardToast.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinator.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorView.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinator.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinatorView.swift
  Projects/Features/Coordinator/SaveURLCoordinator/SaveURLCoordinator.swift
  Projects/Features/Coordinator/SaveURLCoordinator/SaveURLCoordinatorView.swift
  Projects/Features/Coordinator/TabCoordinator/TabCoordinator.swift
  Projects/Features/Coordinator/TabCoordinator/TabCoordinatorView.swift
  Projects/Features/Scene/CreateNewFolderScene/CreateNewFolder.swift
  Projects/Features/Scene/CreateNewFolderScene/CreateNewFolderView.swift
  Projects/Features/Scene/HomeScene/Home.swift
  Projects/Features/Scene/HomeScene/HomeView.swift
  Projects/Features/Scene/HomeScene/Reducer/ClipboardToastFeature.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/SaveURLScene/Reducer/ClipboardToastFeature.swift
  Projects/Features/Scene/SaveURLScene/SaveURL.swift
  Projects/Features/Scene/SaveURLScene/SaveURLView.swift
  Projects/Features/Scene/SelectFolderScene/SelectFolder.swift
  Projects/Features/Scene/SelectFolderScene/SelectFolderView.swift
  Projects/Features/Scene/StorageBoxScene/StorageBoxView.swift
Labels: FEATURE

#47 보관함 메인 뷰 UI (#30)
  Projects/Core/Models/StorageBoxModel.swift
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_chevron_right_m.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_chevron_right_m.imageset/ic_chevron_right_m.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_chevron_right_m.imageset/ic_chevron_right_m@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_chevron_right_m.imageset/ic_chevron_right_m@3x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_delete.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_delete.imageset/ic_delete.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_delete.imageset/ic_delete@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_delete.imageset/ic_delete@3x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_name_edit.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_name_edit.imageset/ic_name_edit.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_name_edit.imageset/ic_name_edit@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_name_edit.imageset/ic_name_edit@3x.png
  Projects/Features/Coordinator/FeedCoordinator/FeedCoordinator.swift
  Projects/Features/Coordinator/FeedCoordinator/FeedCoordinatorView.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Coordinator/StorageBoxCoordinator/StorageBoxCoordinator.swift
  Projects/Features/Coordinator/StorageBoxCoordinator/StorageBoxCoordinatorView.swift
  Projects/Features/Scene/FeedScene/Feed.swift
  Projects/Features/Scene/FeedScene/FeedView.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/StorageBoxScene/StorageBox.swift
  Projects/Features/Scene/StorageBoxScene/StorageBoxView.swift
  Projects/Features/Scene/StorageBoxScene/ViewModifiers/EditFolderPopupModifier.swift
  Projects/Features/Scene/StorageBoxScene/ViewModifiers/NewFolderPopupModifier.swift
  Projects/Features/Scene/StorageBoxScene/Views/StorageBoxItem.swift
  Projects/Features/Scene/StorageBoxScene/Views/StorageBoxSection.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE

#55 온보딩 화면 구현
  Projects/DesignSystem/DesignSystemKit/Sources/Extensions/DesignSystemKitAsset+Typography.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinator.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorView.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/OnboardingScene/Onboarding.swift
  Projects/Features/Scene/OnboardingScene/OnboardingView.swift
  Projects/Features/Scene/OnboardingScene/View/FlowLayout.swift
  Projects/Features/Scene/OnboardingScene/View/FlowLayoutView.swift
  Projects/Features/Scene/OnboardingScene/View/KeywordView.swift
  Projects/Features/Scene/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE

#58 스플래쉬 뷰 구현
  Projects/App/Resources/Assets.xcassets/winter.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/winter.imageset/winter.png
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/winter.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/winter.imageset/winter.png
  Projects/Features/Coordinator/AppCoordinator/AppCoordinator.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/SplashScene/Splash.swift
  Projects/Features/Scene/SplashScene/SplashView.swift
Labels: FEATURE

#60 네트워크 구현
  .gitignore
  Projects/Core/Project.swift
  Projects/Core/Services/KeychainClient.swift
  Projects/Core/Services/NetworkFoundation/APIRepresentable.swift
  Projects/Core/Services/NetworkFoundation/BaseResponse.swift
  Projects/Core/Services/NetworkFoundation/BodyParameters.swift
  Projects/Core/Services/NetworkFoundation/Provider.swift
  Projects/Core/Services/NetworkFoundation/RequestInterceptor.swift
  Projects/Core/Services/NetworkFoundation/Secrets.swift
  Projects/Core/Services/NetworkFoundation/URL+init.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE

#62 온보딩 디자인 변경
  Projects/DesignSystem/DesignSystemKit/Sources/ViewModifiers/Border.swift
  Projects/DesignSystem/DesignSystemKit/Sources/ViewModifiers/CornerRadius.swift
  Projects/DesignSystem/DesignSystemKit/Sources/ViewModifiers/Toast.swift
  Projects/Features/Scene/OnboardingScene/View/KeywordView.swift
Labels: DESIGN

#64 AI 분류화면 구현
  Projects/Core/Models/Card.swift
  Projects/Core/Models/Folder.swift
  Projects/Core/Models/Keyword.swift
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_ai.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_ai.imageset/ic_ai.svg
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Images.xcassets/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Images.xcassets/Sample.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Images.xcassets/Sample.imageset/Sample@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Images.xcassets/Sample.imageset/Sample@3x.png
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKClassificationCard.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKTag.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Extensions/DesignSystemKitAsset+Color.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinator.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinatorView.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/AIClassificationScene/AIClassification.swift
  Projects/Features/Scene/AIClassificationScene/AIClassificationView.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationCardView/AIClassificationCard.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationCardView/AIClassificationCardView.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationCardView/Views/AIClassificationCardEmptyView.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationCardView/Views/AIClassificationCardSectionHeaderView.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationCardView/Views/AIClassificationCardSectionItemView.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationTabView/AIClassificationTab.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationTabView/AIClassificationTabView.swift
  Projects/Features/Scene/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE

#67 홈 화면 배너 구현
  Projects/App/InfoPlists/Info.plist
  Projects/Core/Common/dummy.swift
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_arrow.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_arrow.imageset/ic_arrow@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_arrow.imageset/ic_arrow@3x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_dot.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_dot.imageset/ic_dot@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_dot.imageset/ic_dot@3x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_dot_fill.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_dot_fill.imageset/ic_dot_fill@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_dot_fill.imageset/ic_dot_fill@3x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_star.imageset/ic_star@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_star.imageset/ic_star@3x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_star_fill.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_star_fill.imageset/ic_star_fill@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_star_fill.imageset/ic_star_fill@3x.png
  Projects/DesignSystem/DesignSystemKit/Sources/Buttons/BannerButton.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Extensions/DesignSystemKitAsset+Color.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Home/LKBannerView.swift
  Projects/DesignSystem/DesignSystemUI/Sources/Atomic/BannerButtonPreview.swift
  Projects/DesignSystem/DesignSystemUI/Sources/ContentView.swift
  Projects/Features/Coordinator/StorageBoxCoordinator/StorageBoxCoordinatorView.swift
  Projects/Features/Scene/HomeScene/Home.swift
  Projects/Features/Scene/HomeScene/HomeBannerPageControlView.swift
  Projects/Features/Scene/HomeScene/HomeBannerType.swift
  Projects/Features/Scene/HomeScene/HomeView.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/WebScene/dummy.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE

#69 토스트 메세지가 탭 바에 가려지는 버그 수정
  Projects/Features/Scene/HomeScene/HomeContainerView.swift
  Projects/Features/Scene/HomeScene/HomeView.swift
Labels: BUG

#72 홈 상세 플로우 구현
  Projects/DesignSystem/DesignSystemKit/Sources/Extensions/DesignSystemKitAsset+Color.swift
  Projects/DesignSystem/DesignSystemKit/Sources/FolderBottomSheet/FolderBottomSheet.swift
  Projects/DesignSystem/DesignSystemKit/Sources/ViewModifiers/BottomSheet.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinator.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinatorView.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/CreateNewFolderScene/CreateNewFolder.swift
  Projects/Features/Scene/HomeScene/Home.swift
  Projects/Features/Scene/HomeScene/HomeContainerView.swift
  Projects/Features/Scene/HomeScene/HomeView.swift
  Projects/Features/Scene/HomeScene/Reducer/HomeOverlayComponent+View.swift
  Projects/Features/Scene/HomeScene/Reducer/HomeOverlayComponent.swift
Labels: FEATURE

#73 홈 화면 빈 페이지 뷰, 그라디언트 뷰 추가
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_empty.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_empty.imageset/ic_empty@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_empty.imageset/ic_empty@3x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Images.xcassets/ic_tempgif.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Images.xcassets/ic_tempgif.imageset/ic_tempgif@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Images.xcassets/ic_tempgif.imageset/ic_tempgif@3x.png
  Projects/DesignSystem/DesignSystemKit/Sources/TopScrollBar/LKTopScrollBar.swift
  Projects/DesignSystem/DesignSystemUI/Sources/Component/FolderBottomSheetPreview.swift
  Projects/Features/Scene/HomeScene/Home.swift
  Projects/Features/Scene/HomeScene/HomeBanner/HomeBannerPageControlView.swift
  Projects/Features/Scene/HomeScene/HomeBanner/HomeBannerType.swift
  Projects/Features/Scene/HomeScene/HomeBanner/HomeBannerView.swift
  Projects/Features/Scene/HomeScene/HomeCardEmptyView.swift
  Projects/Features/Scene/HomeScene/HomeView.swift
Labels: DESIGN

#77 오픈소스 라이센스 추가
  Projects/App/Resources/Settings.bundle/LINKIT.latest_result.txt
  Projects/App/Resources/Settings.bundle/LINKIT.plist
  Projects/App/Resources/Settings.bundle/LINKIT/ACarousel.plist
  Projects/App/Resources/Settings.bundle/LINKIT/Alamofire.plist
  Projects/App/Resources/Settings.bundle/LINKIT/FlowStacks.plist
  Projects/App/Resources/Settings.bundle/LINKIT/KeychainAccess.plist
  Projects/App/Resources/Settings.bundle/LINKIT/TCACoordinators.plist
  Projects/App/Resources/Settings.bundle/LINKIT/combine-schedulers.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-case-paths.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-clocks.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-collections.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-composable-architecture.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-concurrency-extras.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-custom-dump.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-dependencies.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-identified-collections.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-perception.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swift-syntax.plist
  Projects/App/Resources/Settings.bundle/LINKIT/swiftui-navigation.plist
  Projects/App/Resources/Settings.bundle/LINKIT/xctest-dynamic-overlay.plist
  Projects/App/Resources/Settings.bundle/Root.plist
  Projects/App/Resources/Settings.bundle/en.lproj/Root.strings
Labels: DOCS

#66 온보딩 API 연결
  Projects/Core/Services/KeychainClient.swift
  Projects/Core/Services/NetworkFoundation/Secrets.swift
  Projects/Core/Services/ResponseDTO/PostUserResponseDTO.swift
  Projects/Core/Services/UserAPI/UserAPI.swift
  Projects/Core/Services/UserAPI/UserAPIClient.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinator.swift
  Projects/Features/Scene/OnboardingScene/Onboarding.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/SplashScene/Splash.swift
Labels: FEATURE

#76 카드 뷰 프로그레스 바, 스켈레톤 뷰 구현
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKCard.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKCardProgressBar.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKDescriptionSkeletonView.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKKeywordSkeletonView.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKSkeletonLine.swift
  Projects/DesignSystem/DesignSystemUI/Sources/Component/LKCardPreview.swift
  Projects/Features/Scene/HomeScene/HomeView.swift
Labels: FEATURE

#91 저장화면 - SelectFolderView API 연결
  Projects/Core/Services/PostAPI/PostAPI.swift
  Projects/Core/Services/PostAPI/PostAPIClient.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinator.swift
  Projects/Features/Scene/SelectFolderScene/SelectFolder.swift
  Projects/Features/Scene/SelectFolderScene/SelectFolderView.swift
Labels: FEATURE

#93 NetworkEventLogger 출력문 개행되도록 수정
  Projects/Core/Services/NetworkFoundation/NetworkEventLogger.swift
Labels: REFACTOR

#101 AI 분류 화면 API 연결(2)
  Projects/Core/Models/Folder.swift
  Projects/Core/Services/AIClassificationAPI/AIClassificationAPI.swift
  Projects/Core/Services/AIClassificationAPI/AIClassificationClient.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKClassificationCard.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinator.swift
  Projects/Features/Scene/AIClassificationScene/AIClassification.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationCardView/AIClassificationCard.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationCardView/AIClassificationCardView.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationTabView/AIClassificationTab.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationTabView/AIClassificationTabView.swift
  Projects/Features/Scene/HomeScene/Home.swift
Labels: FEATURE

#117 AI 분류 화면 내비게이션 연결
  Projects/Features/Coordinator/AIClassificationCoordinator/AIClassificationCoordinator.swift
  Projects/Features/Coordinator/AIClassificationCoordinator/AIClassificationCoordinatorView.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinator.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinatorView.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/AIClassificationScene/AIClassification.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE

#119 get /folder/posts API 수정
  Projects/Core/Services/FolderAPI/FolderAPI.swift
  Projects/Core/Services/FolderAPI/FolderAPIClient.swift
  Projects/Core/Services/ResponseDTO/Common/AISummaryStatusDTO.swift
  Projects/Core/Services/ResponseDTO/Common/CardDTO.swift
  Projects/Core/Services/ResponseDTO/Home/GetFolderPostsResponseDTO.swift
Labels: FEATURE

#127 임시 설정 화면 추가
  Projects/App/Resources/Settings.bundle/Root.plist
  Projects/App/Resources/karina-aespa.gif
  Projects/Features/Coordinator/AppCoordinator/AppCoordinator.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorView.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/SettingScene/Setting.swift
  Projects/Features/Scene/SettingScene/SettingView.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
Labels: FEATURE

#130 스플래쉬, 로딩 인디케이터, 액티비티 뷰 구현
  Projects/App/Resources/Assets.xcassets/winter.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/winter.imageset/winter.png
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/Final/ic_appIcon.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/Final/ic_appIcon.imageset/ic_appIcon@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/Final/ic_appIcon.imageset/ic_appIcon@3x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Lotties/Spinner.json
  Projects/DesignSystem/DesignSystemKit/Resources/Lotties/Splash.json
  Projects/DesignSystem/DesignSystemKit/Sources/ActivityView/ActivityItem.swift
  Projects/DesignSystem/DesignSystemKit/Sources/ActivityView/ActivityView.swift
  Projects/DesignSystem/DesignSystemKit/Sources/LoadingIndicator/LoadingIndicator.swift
  Projects/DesignSystem/DesignSystemKit/Sources/ViewModifiers/ActivitySheet.swift
  Projects/DesignSystem/Project.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinator.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinatorView.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/HomeScene/Home.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/SaveURLVideoGuideScene/SaveURLVideoGuide.swift
  Projects/Features/Scene/SaveURLVideoGuideScene/SaveURLVideoGuideView.swift
  Projects/Features/Scene/SaveURLVideoGuideScene/Views/StepDescriptionView.swift
  Projects/Features/Scene/SaveURLVideoGuideScene/Views/URLActivityItemSource.swift
  Projects/Features/Scene/SaveURLVideoGuideScene/Views/VideoPlayerView.swift
  Projects/Features/Scene/SplashScene/Splash.swift
  Projects/Features/Scene/SplashScene/SplashView.swift
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency.swift
  Tuist/ResourceSynthesizers/JSON.stencil
  Tuist/ResourceSynthesizers/Json.stencil
Labels: FEATURE

#140 홈 작업
  Projects/Core/Services/PostAPI/PostAPI.swift
  Projects/Core/Services/PostAPI/PostAPIClient.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKCardProgressBar.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Card/LKSkeletonLine.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinator.swift
  Projects/Features/Coordinator/HomeCoordinator/HomeCoordinatorView.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/FeedScene/FeedView.swift
  Projects/Features/Scene/HomeScene/Home.swift
Labels: FEATURE

#147 보관함 QA
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_delete.imageset/Contents.json
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_delete.imageset/ic_delete.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_delete.imageset/ic_delete@2x.png
  Projects/DesignSystem/DesignSystemKit/Resources/Images/Icons.xcassets/ic_delete.imageset/ic_delete@3x.png
  Projects/DesignSystem/DesignSystemKit/Sources/ActionSheet/LKActionSheet.swift
  Projects/DesignSystem/DesignSystemKit/Sources/TabBar/LKTabBar.swift
  Projects/DesignSystem/DesignSystemKit/Sources/Toast/LKClipboardToast.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Coordinator/StorageBoxCoordinator/StorageBoxCoordinator.swift
  Projects/Features/Coordinator/StorageBoxCoordinator/StorageBoxCoordinatorView.swift
  Projects/Features/Scene/AIClassificationScene/Views/AIClassificationCardView/Views/AIClassificationCardSectionItemView.swift
  Projects/Features/Scene/ChangeFolderNameScene/ChangeFolderName.swift
  Projects/Features/Scene/CreateNewFolderScene/CreateNewFolder.swift
  Projects/Features/Scene/OnboardingScene/View/FlowLayoutView.swift
  Projects/Features/Scene/StorageBoxScene/StorageBox.swift
  Projects/Features/Scene/StorageBoxScene/StorageBoxContainerView.swift
  Projects/Features/Scene/StorageBoxScene/StorageBoxView.swift
  Projects/Features/Scene/StorageBoxScene/ViewModifiers/EditFolderPopupModifier.swift
  Projects/Features/Scene/StorageBoxScene/ViewModifiers/NewFolderPopupModifier.swift
  Projects/Features/Scene/StorageBoxScene/Views/StorageBoxItem.swift
Labels: FEATURE
